-- Answer #1
SELECT agents.AGENT_CODE,agents.AGENT_NAME,SUM(orders.ORD_AMOUNT) AS TOTAL_ORDER_AMOUNT
FROM agents
INNER JOIN orders ON agents.AGENT_CODE = orders.AGENT_CODE
GROUP BY agents.AGENT_CODE, agents.AGENT_NAME
ORDER BY TOTAL_ORDER_AMOUNT DESC
LIMIT 1;
-- Answer #2
SELECT customer.CUST_CODE,customer.CUST_NAME,SUM(orders.ORD_AMOUNT) AS TOTAL_AMOUNT_SPENT
FROM customer
INNER JOIN  orders ON customer.CUST_CODE = orders.CUST_CODE
GROUP BY customer.CUST_CODE, customer.CUST_NAME
HAVING SUM(orders.ORD_AMOUNT) > 5000.00
ORDER BY TOTAL_AMOUNT_SPENT DESC;
-- Answer #3
SELECT orders.AGENT_CODE, COUNT(*) AS TOTAL_ORDERS_IN_JULY_2008
FROM orders
WHERE YEAR(orders.ORD_DATE) = 2008 AND MONTH(orders.ORD_DATE) = 7
GROUP BY orders.AGENT_CODE
ORDER BY orders.AGENT_CODE;